project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home"
        contents:
          - text: About
            url: index.qmd
      - section: "Lessons"
        contents:
          - lesson-day1-01-intro.qmd
          - lesson-day1-02-import.qmd
      - section: "Practice"
        contents:
          - practice-day1.qmd
      - section: "Solutions"
        contents:
          - solution-day1.qmd
      - section: "Resources"
        contents:
          - resources/functions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



