project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home"
        contents:
          - text: About
            url: index.qmd
      - section: "Lessons"
        contents:
          - d1-01-intro.qmd
          - d1-02-import.qmd
            
      - section: "Practice"
        contents:
          - p1-intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



